
[workspace]
resolver = "2"
members = ["pwa", "cli", "server", "shared", "tauri/src-tauri"]

# ugh, `cargo build` in the root fails, was hoping this helped but did not :/
# [workspace.dependencies]
# shared = { path = "shared", default-features = false, features = ["rust"] }
