[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
sled = "0.34.7"
warp = "0.3"

[dependencies.shared]
path = "../shared"
default-features = false
features = ["rust"]
